algoritmo "contador"
// Função :
// Autor :
// Data : 16/07/2023
// Seção de Declarações 
var
num, valor, salto: inteiro

inicio
// Seção de Comandos

escreva("Quer contar até quanto? ")
leia(valor)
escreva("Quer contar de quanto em quanto? ")
leia(salto)
num <- 0
enquanto (num <= valor) faca
         escreval(num)
         num <- num + salto
fimenquanto
escreval("Terminei de contar")
fimalgoritmo
