algoritmo "semnome"
// Função :
// Autor :
// Data : 26/07/2023
// Seção de Declarações 
var
nota1, nota2, nota3, nota4, media: real
inicio
// Seção de Comandos 

escreva("Insira a primeira nota: ")
leia(nota1)
escreva("Insira a segunda nota: ")
leia(nota2)
escreva("Insira a terceira nota: ")
leia(nota3)
escreva("Insira a quarta nota: ")
leia(nota4)

media <- (nota1+nota2+nota3+nota4)/4

escreval("sua média é: ", media)

fimalgoritmo
